config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  root 'users#index'
  # get '/all_posts', to: 'posts#all_posts'
  resources :users, only: [:index, :show] do
    resources :posts, only: [:index, :show, :new, :create, :destroy]
  end
  # Defines the root path route ("/")
  # root "articles#index"

  resources :posts do
    resources :comments, only: [:create, :destroy]
    resources :likes, only: [:create]
  end
end

app/models/ability.rb
class Ability
  include CanCan::Ability
  def initialize(user)
    user ||= User.new
    # Define User abilities
    # if user.is? :admin
    #   can :manage, Post
    # else
    #   can :read, Post
    # end
    can :read, Post # all users can view posts
    can :read, Comment # all users can view comments
    return unless user.present?

    can :manage, Post, user_id: user.id # only post owners can manage posts
    can :manage, Comment, user_id: user.id # only post owners can manage posts

    return unless user.is? :admin

    can :manage, :all
  end
  #   user ||= User.new # guest user (not logged in)
  #   if user.admin?
  #     can :manage, :all
  #   else
  #     can :read, :all
  #   end
  #
  # The first argument to `can` is the action you are giving the user
  # permission to do.
  # If you pass :manage it will apply to every action. Other common actions
  # here are :read, :create, :update and :destroy.
  #
  # The second argument is the resource the user can perform the action on.
  # If you pass :all it will apply to every resource. Otherwise pass a Ruby
  # class of the resource.
  #
  # The third argument is an optional hash of conditions to further filter the
  # objects.
  # For example, here the user can only update published articles.
  #
  #   can :update, Article, :published => true
  #
  # See the wiki for details:
  # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user
  after_save :update_comments_count

  validates :text, presence: true, length: { minimum: 3 }

  def update_comments_count
    post.increment!(:postsCounter)
  end

  def find_user
    User.find(user_id).name
  end
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :post
  after_save :update_likes_count

  def update_likes_count
    post.increment!(:LikesCounter)
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  # has_many :user_posts

  validates :title, presence: true, length: { minimum: 3 }
  validates :text, presence: true, length: { minimum: 3 }
  validates :postsCounter, :LikesCounter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  def most_recent_posts
    posts = Post.all
    posts.order(created_at: :desc).limit(3)
  end

  def recents_comments
    comments.includes(:post).order(created_at: :desc).limit(3)
  end

  def update_posts_count
    user.increment!(:posts_counter)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
  has_many :posts
  has_many :comments
  has_many :likes

  validates :name, presence: true
  validates :PostsCounter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  def is?(requested_role)
    role == requested_role.to_s
  end

  def most_recent_posts
    Post.where(user_id: id).last(3)
  end

  def update_posts_counter
    postscounter = Post.where(user_id: id).count
    update(PostsCounter: postscounter)
  end
end

app/models/user_post.rb
class UserPost < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :update_allowed_parameters, if: :devise_controller?

  protected

  def update_allowed_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :bio, :password, :password_confirmation) }
    devise_parameter_sanitizer.permit(:account_update) do |u|
      u.permit(:name, :email, :bio, :password, :password_confirmation, :current_password)
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
    @comment = Comment.new
  end

  def create
    @post = Post.find_by_id(params[:post_id])
    @user = User.find_by_id(@post.user_id)
    @comment = Comment.new(comment_params.merge(user_id: current_user.id, post_id: @post.id))

    flash[:notice] = if @comment.save
                       'You commented the post 💬'
                     else
                       'Comment was not created.'
                     end
    redirect_to user_posts_path(@user.id)
  end

  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy
    flash[:notice] = 'You deleted the post 💬'
    redirect_to user_post_path(current_user.id, @comment.post.id)
  end

  private

  def comment_params
    params.require(:data).permit(:text)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def new
    @like = Like.new
  end

  def create
    @post = Post.find(params[:post_id])
    @like = Like.create(user_id: current_user.id)
    flash[:notice] = 'You liked the post ❤️'
    respond_to do |format|
      format.html { redirect_to @post } if @post.save
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  # load_and_authorize_resource

  def new
    @post = Post.new
  end

  def index
    @current_user = current_user
    @user = User.find(params[:user_id])
    @posts = @user.posts.includes(:comments).where(user_id: @user.id).order(:id)
  end

  def create
    @post = Post.new(post_params.merge(user_id: current_user.id))
    @post.user_id = current_user.id
    @post.postsCounter = 0
    @post.LikesCounter = 0
    if @post.save
      flash[:notice] = 'Post was successfully created!!!'
      redirect_to user_post_path(@post.user_id, @post.id)
    else
      render 'new'
      flash[:notice] = 'Post was not created.'
    end
  end

  def update; end

  def edit; end

  def destroy
    @post = Post.find_by_id(params[:id])
    @post.destroy
    redirect_to user_posts_path(current_user.id)
  end

  def all_posts
    @posts = Post.all
  end

  def show
    @post = Post.find_by_id(params[:id])
    @user = User.find_by_id(@post.user_id)
    # @comments = Comment.where(post_id: @post.id)
    @comments = Comment.includes(:post).where(post_id: @post.id)
    # authorize! :read, @post
  end

  private

  def post_params
    params.require(:post).permit(:title, :text)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.order(:id)
  end

  def show
    @user = User.find(params[:id])
    @posts = Post.includes(:user).where(user_id: @user.id).order(:id)
  end

  def create
    @user = User.create(user_params)
    redirect_to @user
  end

  private

  def user_params
    params.require(:user).permit(:name, :bio, :photo)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
  def truncate_text(text)
    "#{text[0..30]}..."
  end

  def posts?(posts)
    posts.empty? ? 'You have no posts yet, Try to add a post 😊' : 'Your recents posts'
  end
end

app/views/posts/_form.html.erb
<h2>Add a new post here. </h2>
<%= simple_form_for @post do |f| %>
<div class="card bg-transparent">
  <div class="card-body">

    <div class="mb-3">
      <%= f.input :title, class: "form-control", placeholder: "Post title" %>
    </div>

    <div class="mb-3">
      <%= f.input :text, as: :text, class: "form-control", placeholder: "Enter your content here ..."%>
    </div>

    <%= f.button :submit, class: "pagination-btn" %>

  </div>
</div>
<% end %>

app/views/posts/_post.html.erb
<div class="post_container">
<%=  link_to user_post_path(user.id, post.id) do%>
     <h2>Post #<%= post.id %></h2>
     <p><%= post.text %></p>
     <div class="d-flex likes-comments-container">
       <span>Comments: <%= post.postsCounter || 0 %></span>
       <span>Likes: <%= post.LikesCounter || 0 %></span>
     </div>
<%end%>
</div>

app/views/posts/all_posts.html.erb
<div class="comments py-3">
  <p id="notice"><%= notice %></p>
  <div class="see-posts">
   <%= link_to "Add post", new_post_path%>
  </div>
  <% @posts.each do |post|%>
    <div class="d-flex flex-column py-3">
      <p><%= post.user.name %></p>
      <ul class="comments-list">
        <% post.most_recent_posts.each do |post| %>
          <li><%= post.text%></li>
        <%end%>
      </ul>
  </div>
  <%end%>
  <div class="pagination-btn">
    <%= link_to "Pagination"%>
  </div>
</div>

app/views/posts/edit.html.erb
<div>
  <%= render "form" %>
</div> 

app/views/posts/index.html.erb
<div class="comments py-3">
  <p id="notice"><%= notice %></p>
  <%= render partial: "layouts/header", locals: {user: @user} %>
  <div class="see-posts">
   <%= link_to "Add post", new_post_path%>
  </div>
  <h2><%= posts?(@posts) %></h3>
  <% @posts.each do |post|%>
    <div class="d-flex flex-column py-3">
      <%= render partial: "posts/post", locals: {post: post, user: @user} %>
      <ul class="comments-list">
        <% post.most_recent_posts.each do |post| %>
          <li> <%= @user.name%> : <%= post.title%></li>
          <li> <%= post.text%> </li>
        <%end%>
      </ul>
  </div>
  <%end%>
  <div class="pagination-btn">
    <%= link_to "Pagination"%>
  </div>
</div>

app/views/posts/new.html.erb
<div class="container form p-2 my-4 border border-dark">
  <%= render "form" %>
</div> 

app/views/posts/show.html.erb
<div class="container py-3 d-flex flex-column">
     <div class= "post_container">
      <div class="post-details">
        <h2>Post Title: #<%= @post.title %> by <%= @user.name%></h2>
        <div class="likes-comments-container">
          <span>Comments: <%= @post.postsCounter || 0 %></span>
          <span>Likes: <%= @post.LikesCounter || 0 %></span>
        </div>
      </div>
      <p><%= @post.text %></p>
     </div>
      <ul class="comments-list">
        <% @comments.each do |comment| %>
          <li> 
          <%= comment.user.name%>
          <%= comment.text%>
          <% if can? :destroy, comment %>
            <%= button_to "X", post_comment_path(@post.id, comment.id), method: :delete %>
          <% end %>
          </li>
        <%end%>
      </ul>
      <%= render partial: "likes/form" %>
      <%= render partial: "comments/form"%>
      <% if can? :destroy, @post %>
      <%= button_to "Delete", user_post_path(@user, @post), method: :delete %>
      <% end %>
</div>